# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO MojaveWastelander/serial
    REF d71bc2f69e2e11cde7d1e740a8a159b1f0858a28
    SHA512 556f7eb79984e092c4bf5a9726e183cbaac42415d58f843dd931c13635037488d810d0fbf6819a9544e206d9cb775a250543ea29341ae40bc79f762fd41f9dda
    HEAD_REF master
)

file(COPY ${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt DESTINATION ${SOURCE_PATH})
file(COPY ${CMAKE_CURRENT_LIST_DIR}/serialConfig.cmake.in DESTINATION ${SOURCE_PATH})

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets()
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
file(COPY
  ${SOURCE_PATH}/readme.md
  DESTINATION ${CURRENT_PACKAGES_DIR}/share/serial
)

file(RENAME ${CURRENT_PACKAGES_DIR}/share/serial/readme.md ${CURRENT_PACKAGES_DIR}/share/serial/copyright)
